<?php
require_once 'core.php';
require_once 'model/home_model.php';

class HomeController extends Core
{
    public function index()
    {
        $model = new HomeModel();
        $getData = $model->dummy();
        parent::loadView('home.php', array('data'=>$getData)); // TODO: Change the autogenerated stub
    }
}